# --- !Ups

create table VEHICLES (
  VEHICLE_ID BIGINT AUTO_INCREMENT,
  NUMBER_PLATE VARCHAR(16) NOT NULL,
  CHECKIN_TIMESTAMP LONG DEFAULT CURRENT_TIMESTAMP,
  CHECKOUT_TIMESTAMP LONG ,
  PRIMARY KEY (VEHICLE_ID)
); 


# --- !Downs

drop table VEHICLES;